import type { NextPage } from 'next';
import Head from 'next/head';
import PageTemplate from '../components/templates/PageTemplate/PageTemplate';
import FirstSection from '../views/FirstSection/FirstSection';
import Footer from '../components/organisms/Footer/Footer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageTemplate>
        <FirstSection />
      </PageTemplate>
      <Footer />
    </div>
  );
};

export default Home;
